---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- name: Ensure timezones are available
  apt:
    name: tzdata
    state: present
  when: ansible_os_family == "Debian"

- name: Check if /etc/localtime is a link
  stat:
    path: /etc/localtime
  register: st


# Workaroud for Ubuntu bug https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
- block:
  - debug:
      msg: "Path exists and is a symlink"
    when: st.stat.islnk is defined and st.stat.islnk == True

  - debug:
      msg: "Link doesnt point to /usr/share/zoneinfo/Europe/Warsaw"
    when: st.stat.islnk is defined and st.stat.lnk_source != "/usr/share/zoneinfo/{{ time_zone }}"

  - name: Remove /etc/localtime [Ubuntu workaround]
    file:
      dest: /etc/localtime
      state: absent
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04") and ( st.stat.islnk is defined and st.stat.lnk_source != "/usr/share/zoneinfo/{{ time_zone }}" )

  - name: Link timezone to localtime [Ubuntu workaround]
    file:
      src: "/usr/share/zoneinfo/{{ time_zone }}"
      dest: /etc/localtime
      state: link
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04") and ( not st.stat.exists)

- name: Set timezone
  timezone:
    name: "{{ time_zone }}"

- include: chrony.yml
  when: time_service == "chrony"

- include: ntpd.yml
  when: time_service == "ntpd"
