---
- name: ensure chrony package is absent
  package:
    name: chrony
    state: absent

- name: Install ntpd
  package:
    name: ntp
    state: present

- name: Set ntpd configuration
  template:
    src: ntp.conf.j2
    dest: "{{ ntpd_conf }}"
  notify: restart ntpd

- block:
  - name: Stop service
    service:
      name: "{{ ntpd_service_name }}"
      state: stopped

  - name: Force time synchronization
    command: "timeout 15s ntpd -gq"
#    register: sync_result
#    until: sync_result.rc == 0
#    retries: 10
#    delay: 5
    ignore_errors: yes
  when: time_force_sync

- name: Ensure ntpd service is enabled
  service:
    name: "{{ ntpd_service_name }}"
    enabled: yes
